markdown: rdiscount
permalink: :title.html
baseurl:chendell.github.io
url: http://chendell.github.io
lsi: true
pygments: true
safe: true
auto: true

# presonal config
title: DreamLand
comments: disqus