markdown: rdiscount
permalink: :title.html
url: http://chendell.github.io
lsi: true
pygments: true
safe: true
auto: true

# presonal config
title: DreamLand
comments: disqus

author:
  name:AChen
  nickname:Achen
  email: shinerene@gmail.com
  site: http://chendell.github.io